name: baseline
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pycocotools=2.0.2
  - pytorch=1.6.0
  - torchvision=0.7.0
  - cudatoolkit=10.1
  - optuna=2.4.0
  - pandas=1.2.1
  - scikit-learn==0.24.1
  - psycopg2==2.8.6
  - pip
  - pip:
    - pycocotools==2.0.2
    - pre-commit==2.9.3
    - split-folders==0.4.3
    - ptflops==0.6.4
    - pycryptodome==3.10.1
    - pyarmor==6.7.0
