input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        # output [24, 48, 96, 192, 1024]
        [1, Conv, [24, 3, 2, null, 1, "ReLU"]],
        [1, MaxPool, [3, 2, 1]],
        [4, ShuffleInvertedResidual, [48]],
        [8, ShuffleInvertedResidual, [96]],
        [4, ShuffleInvertedResidual, [192]],
        [1, Conv, [1024, 1, 1, null, 1, "ReLU"]],
        [1, GlobalAvgPool, []],
        [1, Flatten, []],
        [1, Linear, [9]]
    ]
